model = "gpt-5.6-terra"
model_reasoning_effort = "low"
personality = "pragmatic"
notify = ["/Users/msc8/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[projects."/Users/msc8/code/flowise-buyo"]
trust_level = "trusted"

[projects."/Users/msc8/code/flowise-buyo/buyo-autogen"]
trust_level = "trusted"

[projects."/Users/msc8/code/DeliveranceFlow"]
trust_level = "trusted"

[projects."/Users/msc8/code/openwebui-integration"]
trust_level = "trusted"

[projects."/Users/msc8/code/media_downloader"]
trust_level = "trusted"

[projects."/Users/msc8/code/sootak"]
trust_level = "trusted"

[projects."/Users/msc8/code/buyo-main-backend"]
trust_level = "trusted"

[projects."/Users/msc8/code/arvan-video-uploader"]
trust_level = "trusted"

[projects."/Users/msc8/code/redis-course"]
trust_level = "trusted"

[projects."/Users/msc8/code/Documentation"]
trust_level = "trusted"

[projects."/Users/msc8/code/triangular-arbitrage-bot"]
trust_level = "trusted"

[projects."/Users/msc8/code/FeedForge"]
trust_level = "trusted"

[projects."/Users/msc8/code/NavaMatn"]
trust_level = "trusted"

[mcp_servers.playwright]
command = "npx"
args = ["-y", "@playwright/mcp@latest", "--headless"]

[mcp_servers.node_repl]
args = []
command = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/msc8/.codex:/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
CODEX_HOME = "/Users/msc8/.codex"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_TINYSKY_ENABLED = "1"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = ""
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = ""
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.915.31945"
NODE_REPL_TRUSTED_SERVICES = '{"browser":"/Users/msc8/.codex/plugins/cache/openai-bundled/browser/26.915.31945/scripts/browser-service.mjs","sky":"@oai/sky/service"}'
SKY_CUA_SERVICE_PATH = "/Users/msc8/.codex/computer-use/Codex Computer Use.app"
CODEX_CLI_PATH = "/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[marketplaces.openai-bundled]
source_type = "local"
source = "/Users/msc8/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/Users/msc8/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."codex-app-tools@openai-bundled"]
enabled = true

[plugins."unified-computer-use@openai-bundled"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[desktop]
preventSleepWhileRunning = true
keepRemoteControlAwakeWhilePluggedIn = true
followUpQueueMode = "queue"
dock-icon-preference = "codex-system"

[desktop.open-in-target-preferences]
global = "zed"

[desktop.open-in-target-preferences.perPath]
"/Users/msc8/code/flowise-buyo" = "zed"

[features]
js_repl = false
